name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TestHW01
      id: testhw01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TestHW01
        setup-command: ''
        command: python -m unittest test_formatter.py
        timeout: 5
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTHW01_RESULTS: "${{steps.testhw01.outputs.result}}"
      with:
        runners: testhw01
